/* Minimal viewer for this authored v4 rig. Pixel positions are checked against official Core. */
(async()=>{
 const $=id=>document.getElementById(id),canvas=$('canvas'),gl=canvas.getContext('webgl',{alpha:true,antialias:true,premultipliedAlpha:true,preserveDrawingBuffer:true});
 if(!gl)throw Error('WebGL is unavailable');
 const [spec,motion]=await Promise.all(['rig-spec-v4.json','motions/CatMaid_idle.motion3.json'].map(async u=>{const r=await fetch(u);if(!r.ok)throw Error(u);return r.json();}));
 const parameters=Object.fromEntries(spec.parameters.map(p=>[p.id,p])),values=Object.fromEntries(spec.parameters.map(p=>[p.id,p.default]));
 const defs=Object.fromEntries(spec.deformers.map(d=>[d.id,d]));let playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,time=0,last=performance.now(),blinkStart=null;
 function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}
 const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec2 pos;attribute vec2 uv;varying vec2 tc;uniform vec2 size;void main(){gl_Position=vec4(pos.x/size.x*2.-1.,1.-pos.y/size.y*2.,0.,1.);tc=uv;}'));
 gl.attachShader(program,shader(gl.FRAGMENT_SHADER,'precision mediump float;uniform sampler2D atlas;uniform float opacity;uniform bool wire;varying vec2 tc;void main(){if(wire){gl_FragColor=vec4(.08,.58,.53,.38);}else{vec4 c=texture2D(atlas,tc);gl_FragColor=vec4(c.rgb,c.a*opacity);}}'));
 gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);
 const posLoc=gl.getAttribLocation(program,'pos'),uvLoc=gl.getAttribLocation(program,'uv'),opacityLoc=gl.getUniformLocation(program,'opacity'),wireLoc=gl.getUniformLocation(program,'wire');gl.uniform2f(gl.getUniformLocation(program,'size'),...spec.canvasSize);
 const image=new Image();image.src='atlas.png';await image.decode();const texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL,false);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,image);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);
 gl.enable(gl.BLEND);gl.blendFuncSeparate(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA,gl.ONE,gl.ONE_MINUS_SRC_ALPHA);gl.disable(gl.CULL_FACE);
 const resources=spec.drawables.map(m=>{const vertex=gl.createBuffer(),index=gl.createBuffer(),lines=gl.createBuffer(),array=new Float32Array(m.positions.length*2);for(let i=0;i<m.uvs.length/2;i++){array[4*i+2]=m.uvs[2*i];array[4*i+3]=m.uvs[2*i+1];}gl.bindBuffer(gl.ARRAY_BUFFER,vertex);gl.bufferData(gl.ARRAY_BUFFER,array,gl.DYNAMIC_DRAW);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,index);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(m.indices),gl.STATIC_DRAW);const edges=[];for(let i=0;i<m.indices.length;i+=3){const [a,b,c]=m.indices.slice(i,i+3);edges.push(a,b,b,c,c,a);}gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,lines);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(edges),gl.STATIC_DRAW);return {m,vertex,index,lines,array,edgeCount:edges.length};}).sort((a,b)=>a.m.drawOrder-b.m.drawOrder);
 function sample(n,key){
  const field=n.type==='warp'?'lattice':n.type==='rotation'?'origin':'deltas';
  if(!n.bindings.length)return {geometry:n[field]||Array(n.positions.length).fill(0),opacity:n.opacity,angle:n.angle||0,scale:n.scale||1};
  let terms=[{index:0,weight:1}],stride=1;
  for(const id of n.bindings){const p=parameters[id],v=Math.max(p.min,Math.min(p.max,key[id]??p.default)),keys=p.keys;let low=0;while(low<keys.length-2&&v>keys[low+1])low++;const f=(v-keys[low])/(keys[low+1]-keys[low]);terms=terms.flatMap(t=>[{index:t.index+stride*low,weight:t.weight*(1-f)},{index:t.index+stride*(low+1),weight:t.weight*f}]);stride*=keys.length;}
  const result={geometry:Array(n.keyforms[0][field].length).fill(0),opacity:0,angle:0,scale:0};
  for(const t of terms){const form=n.keyforms[t.index];result.opacity+=t.weight*form.opacity;for(let j=0;j<result.geometry.length;j++)result.geometry[j]+=t.weight*form[field][j];result.angle+=t.weight*(form.angle||0);result.scale+=t.weight*(form.scale||1);}
  return result;
 }
 function evaluated(key){
  const transforms={};
  function transform(id){if(!id)return {apply:(x,y)=>[x,y],opacity:1};if(transforms[id])return transforms[id];const n=defs[id],s=sample(n,key),parent=transform(n.parent);let apply;
   if(n.type==='rotation'){const origin=parent.apply(...s.geometry),a=(s.angle+(n.baseAngle||0))*Math.PI/180;apply=(x,y)=>[origin[0]+s.scale*(Math.cos(a)*x-Math.sin(a)*y),origin[1]+s.scale*(Math.sin(a)*x+Math.cos(a)*y)];}
   else{const cp=[];for(let j=0;j<s.geometry.length;j+=2)cp.push(...parent.apply(s.geometry[j],s.geometry[j+1]));apply=(x,y)=>{const u=Math.max(0,Math.min(n.columns,x*n.columns)),v=Math.max(0,Math.min(n.rows,y*n.rows)),cx=Math.min(n.columns-1,Math.floor(u)),cy=Math.min(n.rows-1,Math.floor(v)),a=u-cx,b=v-cy,i=(cy*(n.columns+1)+cx)*2,j=i+2*(n.columns+1);return [0,1].map(k=>cp[i+k]*(1-a)*(1-b)+cp[i+2+k]*a*(1-b)+cp[j+k]*(1-a)*b+cp[j+2+k]*a*b);};}
   return transforms[id]={apply,opacity:s.opacity*parent.opacity};
  }
  return spec.drawables.map(m=>{const s=sample(m,key),p=transform(m.parent),positions=[];for(let j=0;j<m.positions.length;j+=2)positions.push(...p.apply(m.positions[j]+s.geometry[j],m.positions[j+1]+s.geometry[j+1]));return {id:m.id,positions,opacity:s.opacity*p.opacity};});
 }
 function render(){
  const frame=Object.fromEntries(evaluated(values).map(m=>[m.id,m]));gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);gl.uniform1i(wireLoc,0);
  for(const r of resources){const m=frame[r.m.id];if(m.opacity<=0)continue;for(let i=0;i<m.positions.length/2;i++){r.array[4*i]=m.positions[2*i];r.array[4*i+1]=m.positions[2*i+1];}gl.bindBuffer(gl.ARRAY_BUFFER,r.vertex);gl.bufferSubData(gl.ARRAY_BUFFER,0,r.array);gl.enableVertexAttribArray(posLoc);gl.enableVertexAttribArray(uvLoc);gl.vertexAttribPointer(posLoc,2,gl.FLOAT,false,16,0);gl.vertexAttribPointer(uvLoc,2,gl.FLOAT,false,16,8);gl.uniform1f(opacityLoc,m.opacity);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,r.index);gl.drawElements(gl.TRIANGLES,r.m.indices.length,gl.UNSIGNED_SHORT,0);if($('wire').checked){gl.uniform1i(wireLoc,1);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,r.lines);gl.drawElements(gl.LINES,r.edgeCount,gl.UNSIGNED_SHORT,0);gl.uniform1i(wireLoc,0);}}
 }
 function motionAt(t){for(const c of motion.Curves){const s=c.Segments;let x=s[0],y=s[1],found=false;for(let i=2;i<s.length;i+=3){if(s[i]!==0)throw Error('This draft viewer expects authored linear motion segments');const nx=s[i+1],ny=s[i+2];if(t<=nx){values[c.Id]=y+(ny-y)*(t-x)/(nx-x);found=true;break;}x=nx;y=ny;}if(!found)values[c.Id]=y;}}
 const controls={};for(const p of spec.parameters){const div=document.createElement('div');div.className='slider';div.innerHTML=`<label for="${p.id}">${p.name}<output>0.00</output></label><input type="range" id="${p.id}" min="${p.min}" max="${p.max}" step="0.01" value="${p.default}">`;const target=['ParamHover','ParamBreath','ParamSkirtSway'].includes(p.id)?'primaryControls':p.id.includes('Leg')||p.id.includes('Ankle')?'legControls':'secondaryControls';$(target).append(div);controls[p.id]={input:div.querySelector('input'),out:div.querySelector('output')};controls[p.id].input.addEventListener('input',e=>{playing=false;blinkStart=null;values[p.id]=Number(e.target.value);updateControls();render();});}
 function updateControls(){for(const [id,c] of Object.entries(controls)){c.input.value=values[id];c.out.value=values[id].toFixed(2);}$('play').textContent=playing?'暂停':'播放待机';$('status').textContent=playing?'温柔待机 · 正在播放':'已暂停 · 可调整单个部位';$('time').value=time;$('timeLabel').value=time.toFixed(1)+' / 8 秒';}
 $('play').onclick=()=>{playing=!playing;last=performance.now();updateControls();};$('reset').onclick=()=>{playing=false;blinkStart=null;time=0;for(const p of spec.parameters)values[p.id]=p.default;updateControls();render();};$('blink').onclick=()=>{playing=false;blinkStart=performance.now();};$('time').oninput=e=>{playing=false;time=Number(e.target.value);motionAt(time);updateControls();render();};
 $('compare').onchange=e=>{$('stage').classList.toggle('original',e.target.checked);$('stageLabel').textContent=e.target.checked?'已确认第三版原图':'新角色可动草稿';};$('checker').onchange=e=>$('stage').classList.toggle('checker',e.target.checked);$('wire').onchange=render;
 for(const id of ['play','reset','blink'])$(id).disabled=false;
 window.CatMaid={spec,values,evaluate:evaluated,setValues(v){playing=false;blinkStart=null;Object.assign(values,v);updateControls();render();},reset(){ $('reset').click();},seek(t){playing=false;time=t;motionAt(t);updateControls();render();},play(){playing=true;last=performance.now();updateControls();},isPlaying:()=>playing};
 function tick(now){if(playing){time=(time+Math.min((now-last)/1000,.1))%motion.Meta.Duration;motionAt(time);}if(blinkStart!==null){const t=(now-blinkStart)/1000;values.ParamBlink=Math.max(0,1-abs(t-.16)/.16);if(t>.32){values.ParamBlink=0;blinkStart=null;}}last=now;render();updateControls();requestAnimationFrame(tick);}
 const abs=Math.abs;updateControls();requestAnimationFrame(tick);document.documentElement.dataset.ready='true';
})().catch(error=>{document.getElementById('error').textContent=error.stack||String(error);document.getElementById('status').textContent='加载失败';console.error(error);});
