const fs=require('fs'),path=require('path');
const {chromium}=require('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'verification');
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--no-proxy-server']});
 const context=await browser.newContext({viewport:{width:1340,height:1080},deviceScaleFactor:1,recordVideo:{dir:path.join(ROOT,'cache/video'),size:{width:1340,height:1080}}});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&!r.url().endsWith('favicon.ico'))errors.push(r.status()+' '+r.url());});
 try{
  await page.goto('http://127.0.0.1:18273/production/draft-v001/player.html');await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');
  const anchors=JSON.parse(fs.readFileSync(path.join(OUT,'core-anchors.json')));
  const comparison=await page.evaluate(anchors=>{let maxPixelError=0,maxOpacityError=0,points=0;for(const a of anchors){const actual=Object.fromEntries(CatMaid.evaluate(a.values).map(m=>[m.id,m]));for(const expected of a.meshes){const m=actual[expected.id];if(!m||m.positions.length!==expected.positionsPx.length)throw Error('Mesh layout mismatch');for(let j=0;j<m.positions.length;j++){maxPixelError=Math.max(maxPixelError,Math.abs(m.positions[j]-expected.positionsPx[j]));points++;}maxOpacityError=Math.max(maxOpacityError,Math.abs(m.opacity-expected.opacity));}}return {anchors:anchors.length,coordinateComponents:points,maxPixelError,maxOpacityError};},anchors);
  if(comparison.maxPixelError>.03||comparison.maxOpacityError>1e-5)throw Error('Preview/Core mismatch: '+JSON.stringify(comparison));
  const isolation=await page.evaluate(()=>{CatMaid.reset();const base=Object.fromEntries(CatMaid.evaluate(CatMaid.values).map(m=>[m.id,m]));const tests={ParamLegScreenL:['LegScreenL'],ParamLegScreenR:['LegScreenR'],ParamAnkleScreenL:['LegScreenL'],ParamTailSway:['Tail'],ParamHairScreenL:['HairScreenL']};const result=[];for(const [id,expected] of Object.entries(tests)){const pose={...CatMaid.values,[id]:1};const affected=CatMaid.evaluate(pose).filter(m=>m.positions.some((v,j)=>Math.abs(v-base[m.id].positions[j])>.001)).map(m=>m.id);if(JSON.stringify(affected)!==JSON.stringify(expected))throw Error('Isolation '+id+': '+affected);result.push({parameter:id,affected});}const breathed=Object.fromEntries(CatMaid.evaluate({...CatMaid.values,ParamBreath:1}).map(m=>[m.id,m]));const hands=[];for(const [id,x,y] of [['ArmScreenL',230,784],['ArmScreenR',800,784]]){const b=base[id];let nearest=0,best=Infinity;for(let j=0;j<b.positions.length;j+=2){const d=Math.hypot(b.positions[j]-x,b.positions[j+1]-y);if(d<best){best=d;nearest=j;}}const drift=Math.hypot(breathed[id].positions[nearest]-b.positions[nearest],breathed[id].positions[nearest+1]-b.positions[nearest+1]);if(drift>.15)throw Error('Hand support drift');hands.push({id,nearestVertexDistancePx:best,breathDriftPx:drift});}return {controls:result,handAnchors:hands};});
  await page.getByRole('button',{name:'恢复默认姿势'}).click();await page.screenshot({path:path.join(OUT,'player-default.png'),fullPage:true});
  await page.evaluate(()=>CatMaid.setValues({ParamBlink:1}));await page.locator('#canvas').screenshot({path:path.join(OUT,'blink-closed-preview.png')});
  await page.getByLabel('透明背景',{exact:true}).check();await page.evaluate(()=>CatMaid.seek(4));await page.locator('#canvas').screenshot({path:path.join(OUT,'transparency-preview.png')});await page.getByLabel('透明背景',{exact:true}).uncheck();
  await page.getByLabel('原图对照',{exact:true}).check();if(!await page.locator('#original').isVisible())throw Error('Reference toggle');await page.getByLabel('原图对照',{exact:true}).uncheck();
  await page.evaluate(()=>{CatMaid.seek(0);CatMaid.play();});const first=await page.locator('#canvas').screenshot();
  const performance=await page.evaluate(()=>new Promise(resolve=>{const start=window.performance.now();let frames=0;function tick(now){frames++;if(now-start>8200)resolve({frames,seconds:(now-start)/1000});else requestAnimationFrame(tick);}requestAnimationFrame(tick);}));
  const second=await page.locator('#canvas').screenshot();if(first.equals(second))throw Error('Idle did not advance');
  await page.setViewportSize({width:390,height:844});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw Error('Mobile horizontal overflow');
  await page.screenshot({path:path.join(OUT,'player-mobile.png'),fullPage:true});
  const result={ok:!errors.length,errors,comparison,isolation,referenceToggle:true,transparentToggle:true,idleAdvanced:true,performance,mobileOverflow:overflow,checkedAt:new Date().toISOString()};fs.writeFileSync(path.join(OUT,'browser-summary.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));if(errors.length)process.exitCode=1;
 }finally{const video=await page.video().path();await context.close();fs.copyFileSync(video,path.join(OUT,'player-session.webm'));await browser.close();}
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
